/*
  Q1FieldMan.h

  Field Manager Class
  Read Field Data generated by Tosca

*/

#ifndef Q1FieldMan_h

#define Q1FieldMan_h 1

#include <string>
#include <vector>

class Q1FieldMan
{
private:
  std::string FieldMapFileName;
public:
  Q1FieldMan( const std::string & filename )
    : FieldMapFileName(filename), Nx(0), Ny(0), Nz(0)
  {}
  ~Q1FieldMan()  { cleanupMap(); }

  Q1FieldMan() {}
private:
  Q1FieldMan( const Q1FieldMan & );
  Q1FieldMan & operator = ( const Q1FieldMan & );

public:
  bool Initialize( void );
  double GetReff( double phi, double z=0. ) const;
  bool GetFieldValue( const double point[3], double *Bfield ) const; 

private:
  struct FD {
    float x, y, z;
  }; 
  typedef std::vector < std::vector < std::vector < FD > > > FDContainer;

  FDContainer B;
  // Initial point
  double X0, Y0, Z0;
  // cell size
  double dX, dY, dZ;
  // Number of cell
  int Nx, Ny, Nz;

  //  FILE *out;

  void cleanupMap( void );
};
#endif



