/*
  Q2FieldMan.h

  Field Manager Class
  Read Field Data generated by Tosca

*/

#ifndef Q2FieldMan_h

#define Q2FieldMan_h 1

#include <string>
#include <vector>

class Q2FieldMan
{
private:
  std::string FieldMapFileName;
public:
  Q2FieldMan( const std::string & filename )
    : FieldMapFileName(filename), Nx(0), Ny(0), Nz(0)
  {}
  ~Q2FieldMan()  { cleanupMap(); }

  Q2FieldMan() {}
private:
  Q2FieldMan( const Q2FieldMan & );
  Q2FieldMan & operator = ( const Q2FieldMan & );

public:
  bool Initialize( void );
  double GetReff( double phi, double z=0. ) const;
  bool GetFieldValue( const double point[3], double *Bfield ) const; 

private:
  struct FD {
    float x, y, z;
  }; 
  typedef std::vector < std::vector < std::vector < FD > > > FDContainer;

  FDContainer B;
  // Initial point
  double X0, Y0, Z0;
  // cell size
  double dX, dY, dZ;
  // Number of cell
  int Nx, Ny, Nz;

  //  FILE *out;

  void cleanupMap( void );
};
#endif



