/*
  SplitterFieldMan.h

  Field Manager Class
  Read Field Data generated by Tosca

*/

#ifndef SplitterFieldMan_h

#define SplitterFieldMan_h 1

#include <string>
#include <vector>

class SplitterFieldMan
{
private:
  std::string FieldMapFileName;
public:
  SplitterFieldMan( const std::string & filename )
    : FieldMapFileName(filename), Nx(0), Ny(0), Nz(0)
  {}
  ~SplitterFieldMan()  { cleanupMap(); }
  SplitterFieldMan();
private:
  SplitterFieldMan( const SplitterFieldMan & );
  SplitterFieldMan & operator = ( const SplitterFieldMan & );

public:
  bool Initialize( void );
  double GetReff( double phi, double z=0. ) const;
  bool GetFieldValue( const double point[3], double *Bfield ) const; 

private:
  struct FD {
    float x, y, z;
  }; 
  typedef std::vector < std::vector < std::vector < FD > > > FDContainer;

  FDContainer B;
  // Initial point
  double X0, Y0, Z0;
  // cell size
  double dX, dY, dZ;
  // Number of cell
  int Nx, Ny, Nz;

  void cleanupMap( void );
};
#endif



